server:
  port: 8083
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql:///msns?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  rabbitmq:
    username: msns
    password: msns
    virtual-host: /msns
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 10 #10秒不发送就过期
    lease-renewal-interval-in-seconds: 5 #5秒发送一次心跳
logging:
  level:
    root: DEBUG