server:
  port: 10010
spring:
  application:
    name: msns-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api
  routes:
    dynamic-service: /dynamic/**
    music-service: /music/**
    user-service: /user/**
    admin-service: /admin/**
    comment-service: /comment/**
    favor-service: /favor/**
    like-service: /like/**
    search-service: /search/**
    auth-service: /auth/**
  ignored-patterns: /upload/**
  ignored-services:
    - upload-service
  add-host-header: true
  sensitive-headers:
msns:
  jwt:
    pubKeyPath: D:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: MSNS_TOKEN #cookie名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user
      - /api/music
      - /api/comment
      - /api/favor
      - /api/like
      - /api/dynamic
      - /api/admin
logging:
  level:
    root: DEBUG