server:
  port: 10000
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /file/**
  resources:   #配置静态资源拦截方式和静态资源路径
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${filePath}
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
#配置本地资源路径，必须以/结尾
filePath: d:/msns/
#fdfs:
#  so-timeout: 1501 # 超时时间
#  connect-timeout: 601 # 连接超时时间
#  thumb-image: # 缩略图
#    width: 60
#    height: 60
#  tracker-list: # tracker地址：虚拟机服务器地址+端口（默认是22122）
#    - 192.168.12.18:22122
logging:
  level:
    root: DEBUG
